# Generated by Django 5.2.16 on 2026-07-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_backfill_task_owner"),
        ("todo", "0006_task_management_fields"),
    ]

    operations = []
