# Generated by Django 6.0.6 on 2026-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_task_recurrence_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
